spring:
  application:
    name: nickolas_mariana_ocireu

  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    driver-class-name: org.postgresql.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9998