spring:
  application:
    name: nickolas_mariana_ocireu

  datasource:
    url: jdbc:postgresql://ep-lucky-bonus-an1vd7nt-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: "npg_9jxhbLTkKp1l"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9998